plugins {
    id 'com.android.application'
}

android {
    namespace 'com.etc.hotspotbridge'
    compileSdk 34

    defaultConfig {
        applicationId "com.etc.hotspotbridge"
        minSdk 28          // Android 9 (G3i)
        targetSdk 28       // mantiene el comportamiento clasico de SoftAP por reflexion
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // Alinea todas las libs de Kotlin y evita el choque
    // kotlin-stdlib vs kotlin-stdlib-jdk8 (Duplicate class CollectionsJDK8Kt).
    implementation platform('org.jetbrains.kotlin:kotlin-bom:1.8.22')

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core:1.12.0'

    // Generador de código QR (para unir el teléfono a la red con un escaneo).
    implementation 'com.google.zxing:core:3.5.2'
}
